;; Custom functions ========================================

;; JavaScript / TypeScript indentation style switching
(require 'js2-mode)
(require 'typescript-mode)
(require 'web-mode)
(defun js-set-indent4 ()
  (interactive)
  (setq js-indent-level 4)
  (setq typescript-indent-level 4)
  (setq web-mode-attr-indent-offset 4)
  (setq web-mode-code-indent-offset 4)
  (setq web-mode-css-indent-offset 4)
  (setq web-mode-markup-indent-offset 4))
(defun js-set-indent2 ()
  (interactive)
  (setq js-indent-level 2)
  (setq typescript-indent-level 2)
  (setq web-mode-attr-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-markup-indent-offset 2))
